
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CHASSIS_OD_H
#define CHASSIS_OD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CHASSIS_OD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CHASSIS_OD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CHASSIS_OD_Data;
extern UNS8 Write_Outputs_8_Bit[2];		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */

#endif // CHASSIS_OD_H
