
/* File generated by gen_cfile.py. Should not be modified. */

#include "LIFTER_OD.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Write_Outputs_8_Bit[] =		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 LIFTER_OD_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 LIFTER_OD_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 LIFTER_OD_iam_a_slave = 1;

TIMER_HANDLE LIFTER_OD_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 LIFTER_OD_obj1000 = 0x0;	/* 0 */
                    subindex LIFTER_OD_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 LIFTER_OD_obj1001 = 0x0;	/* 0 */
                    subindex LIFTER_OD_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 LIFTER_OD_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t LIFTER_OD_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex LIFTER_OD_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 LIFTER_OD_obj1005 = 0x0;	/* 0 */
                    ODCallback_t LIFTER_OD_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex LIFTER_OD_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 LIFTER_OD_obj1006 = 0x0;	/* 0 */
                    ODCallback_t LIFTER_OD_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex LIFTER_OD_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1006 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 LIFTER_OD_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 LIFTER_OD_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 LIFTER_OD_obj1014 = 0x80;	/* 128 */
                    subindex LIFTER_OD_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 LIFTER_OD_highestSubIndex_obj1016 = 0;
                    UNS32 LIFTER_OD_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 LIFTER_OD_obj1017 = 0x1000;	/* 4096 */
                    ODCallback_t LIFTER_OD_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex LIFTER_OD_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&LIFTER_OD_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 LIFTER_OD_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 LIFTER_OD_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 LIFTER_OD_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex LIFTER_OD_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 LIFTER_OD_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex LIFTER_OD_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 LIFTER_OD_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LIFTER_OD_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LIFTER_OD_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LIFTER_OD_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 LIFTER_OD_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex LIFTER_OD_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LIFTER_OD_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LIFTER_OD_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1400_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1600[] = 
                    {
                      0x62000108,	/* 1644167432 */	//Control word
                      0x62000208	/* 1644167688 */	//Speed word
                    };
                    ODCallback_t LIFTER_OD_Index1600_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LIFTER_OD_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1600[1] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 LIFTER_OD_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 LIFTER_OD_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 LIFTER_OD_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 LIFTER_OD_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 LIFTER_OD_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t LIFTER_OD_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LIFTER_OD_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&LIFTER_OD_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&LIFTER_OD_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_obj1800_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 LIFTER_OD_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 LIFTER_OD_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex LIFTER_OD_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&LIFTER_OD_obj1A00[7] }
                     };

/* index 0x6200 :   Mapped variable Write Outputs 8 Bit */
                    UNS8 LIFTER_OD_highestSubIndex_obj6200 = 2; /* number of subindex - 1*/
                    ODCallback_t Write_Outputs_8_Bit_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex LIFTER_OD_Index6200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&LIFTER_OD_highestSubIndex_obj6200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[1] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable LIFTER_OD_objdict[] = 
{
  { (subindex*)LIFTER_OD_Index1000,sizeof(LIFTER_OD_Index1000)/sizeof(LIFTER_OD_Index1000[0]), 0x1000},
  { (subindex*)LIFTER_OD_Index1001,sizeof(LIFTER_OD_Index1001)/sizeof(LIFTER_OD_Index1001[0]), 0x1001},
  { (subindex*)LIFTER_OD_Index1005,sizeof(LIFTER_OD_Index1005)/sizeof(LIFTER_OD_Index1005[0]), 0x1005},
  { (subindex*)LIFTER_OD_Index1006,sizeof(LIFTER_OD_Index1006)/sizeof(LIFTER_OD_Index1006[0]), 0x1006},
  { (subindex*)LIFTER_OD_Index1014,sizeof(LIFTER_OD_Index1014)/sizeof(LIFTER_OD_Index1014[0]), 0x1014},
  { (subindex*)LIFTER_OD_Index1017,sizeof(LIFTER_OD_Index1017)/sizeof(LIFTER_OD_Index1017[0]), 0x1017},
  { (subindex*)LIFTER_OD_Index1018,sizeof(LIFTER_OD_Index1018)/sizeof(LIFTER_OD_Index1018[0]), 0x1018},
  { (subindex*)LIFTER_OD_Index1200,sizeof(LIFTER_OD_Index1200)/sizeof(LIFTER_OD_Index1200[0]), 0x1200},
  { (subindex*)LIFTER_OD_Index1400,sizeof(LIFTER_OD_Index1400)/sizeof(LIFTER_OD_Index1400[0]), 0x1400},
  { (subindex*)LIFTER_OD_Index1600,sizeof(LIFTER_OD_Index1600)/sizeof(LIFTER_OD_Index1600[0]), 0x1600},
  { (subindex*)LIFTER_OD_Index1800,sizeof(LIFTER_OD_Index1800)/sizeof(LIFTER_OD_Index1800[0]), 0x1800},
  { (subindex*)LIFTER_OD_Index1A00,sizeof(LIFTER_OD_Index1A00)/sizeof(LIFTER_OD_Index1A00[0]), 0x1A00},
  { (subindex*)LIFTER_OD_Index6200,sizeof(LIFTER_OD_Index6200)/sizeof(LIFTER_OD_Index6200[0]), 0x6200},
};

const indextable * LIFTER_OD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = LIFTER_OD_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = LIFTER_OD_Index1006_callbacks; break;
		case 0x1014: i = 4;break;
		case 0x1017: i = 5;*callbacks = LIFTER_OD_Index1017_callbacks; break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1600: i = 9;*callbacks = LIFTER_OD_Index1600_callbacks; break;
		case 0x1800: i = 10;*callbacks = LIFTER_OD_Index1800_callbacks; break;
		case 0x1A00: i = 11;break;
		case 0x6200: i = 12;*callbacks = Write_Outputs_8_Bit_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &LIFTER_OD_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status LIFTER_OD_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index LIFTER_OD_firstIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const quick_index LIFTER_OD_lastIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  10, /* PDO_TRS */
  11 /* PDO_TRS_MAP */
};

const UNS16 LIFTER_OD_ObjdictSize = sizeof(LIFTER_OD_objdict)/sizeof(LIFTER_OD_objdict[0]); 

CO_Data LIFTER_OD_Data = CANOPEN_NODE_DATA_INITIALIZER(LIFTER_OD);

