
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef LIFTER_OD_H
#define LIFTER_OD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 LIFTER_OD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * LIFTER_OD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data LIFTER_OD_Data;
extern UNS8 Write_Outputs_8_Bit[2];		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */

#endif // LIFTER_OD_H
