
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict_CAN1.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict_CAN1_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict_CAN1_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

//const UNS8 ObjDict_CAN1_iam_a_slave = 0; //Original
const UNS8 ObjDict_CAN1_iam_a_slave = 1; //Jim Test

TIMER_HANDLE ObjDict_CAN1_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict_CAN1_obj1000 = 0x0;	/* 0 */
                    subindex ObjDict_CAN1_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict_CAN1_obj1001 = 0x0;	/* 0 */
                    subindex ObjDict_CAN1_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_CAN1_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict_CAN1_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict_CAN1_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict_CAN1_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_CAN1_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict_CAN1_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 ObjDict_CAN1_obj1005 = 0x0;	/* 0 */
                    ODCallback_t ObjDict_CAN1_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_CAN1_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 ObjDict_CAN1_obj1006 = 0x0;	/* 0 */
                    ODCallback_t ObjDict_CAN1_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_CAN1_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1006 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict_CAN1_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ObjDict_CAN1_highestSubIndex_obj1016 = 0;
                    UNS32 ObjDict_CAN1_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 ObjDict_CAN1_obj1017 = 0x1000;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict_CAN1_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ObjDict_CAN1_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 ObjDict_CAN1_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 ObjDict_CAN1_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 ObjDict_CAN1_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex ObjDict_CAN1_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_CAN1_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_CAN1_obj1018_Serial_Number }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable ObjDict_CAN1_objdict[] = 
{
  { (subindex*)ObjDict_CAN1_Index1000,sizeof(ObjDict_CAN1_Index1000)/sizeof(ObjDict_CAN1_Index1000[0]), 0x1000},
  { (subindex*)ObjDict_CAN1_Index1001,sizeof(ObjDict_CAN1_Index1001)/sizeof(ObjDict_CAN1_Index1001[0]), 0x1001},
  { (subindex*)ObjDict_CAN1_Index1005,sizeof(ObjDict_CAN1_Index1005)/sizeof(ObjDict_CAN1_Index1005[0]), 0x1005},
  { (subindex*)ObjDict_CAN1_Index1006,sizeof(ObjDict_CAN1_Index1006)/sizeof(ObjDict_CAN1_Index1006[0]), 0x1006},
  { (subindex*)ObjDict_CAN1_Index1018,sizeof(ObjDict_CAN1_Index1018)/sizeof(ObjDict_CAN1_Index1018[0]), 0x1018},
};

const indextable * ObjDict_CAN1_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;*callbacks = ObjDict_CAN1_Index1005_callbacks; break;
		case 0x1006: i = 3;*callbacks = ObjDict_CAN1_Index1006_callbacks; break;
		case 0x1018: i = 4;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict_CAN1_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDict_CAN1_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index ObjDict_CAN1_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index ObjDict_CAN1_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 ObjDict_CAN1_ObjdictSize = sizeof(ObjDict_CAN1_objdict)/sizeof(ObjDict_CAN1_objdict[0]); 

CO_Data ObjDict_CAN1_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict_CAN1);

