
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TEST_LIFTER_H
#define TEST_LIFTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 _valueRangeTest (UNS8 typeValue, void * value);
const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data _Data;
extern UNS8 Write_Outputs_8_Bit[2];		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */

#endif // TEST_LIFTER_H
