
/* File generated by gen_cfile.py. Should not be modified. */

#include "TEST_LIFTER.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Write_Outputs_8_Bit[] =		/* Mapped at index 0x6200, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 _valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 _bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 _iam_a_slave = 1;

TIMER_HANDLE _heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 _obj1000 = 0x10191;	/* 65937 */
                    subindex _Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 _obj1001 = 0x0;	/* 0 */
                    subindex _Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_obj1001 }
                     };

/* index 0x1002 :   Manufacturer Status Register. */
                    UNS32 _obj1002 = 0x0;	/* 0 */
                    subindex _Index1002[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1002 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 _highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 _obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t _Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex _Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 _obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 _obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 _obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 _obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 _obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 _highestSubIndex_obj1016 = 0;
                    UNS32 _obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 _obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 _highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 _obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 _obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 _obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 _obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex _Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 _highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 _obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 _obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    ODCallback_t _Index1200_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 _highestSubIndex_obj1400 = 3; /* number of subindex - 1*/
                    UNS32 _obj1400_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 _obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 _obj1400_Inhibit_Time = 0x0;	/* 0 */
                    ODCallback_t _Index1400_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&_obj1400_Inhibit_Time }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 _highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
                    UNS32 _obj1600[] = 
                    {
                      0x62000108,	/* 1644167432 */
                      0x62000208	/* 1644167688 */
                    };
                    ODCallback_t _Index1600_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex _Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&_obj1600[1] }
                     };

/* index 0x6200 :   Mapped variable Write Outputs 8 Bit */
                    UNS8 _highestSubIndex_obj6200 = 2; /* number of subindex - 1*/
                    subindex _Index6200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&_highestSubIndex_obj6200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[1] }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable _objdict[] = 
{
  { (subindex*)_Index1000,sizeof(_Index1000)/sizeof(_Index1000[0]), 0x1000},
  { (subindex*)_Index1001,sizeof(_Index1001)/sizeof(_Index1001[0]), 0x1001},
  { (subindex*)_Index1002,sizeof(_Index1002)/sizeof(_Index1002[0]), 0x1002},
  { (subindex*)_Index1018,sizeof(_Index1018)/sizeof(_Index1018[0]), 0x1018},
  { (subindex*)_Index1200,sizeof(_Index1200)/sizeof(_Index1200[0]), 0x1200},
  { (subindex*)_Index1400,sizeof(_Index1400)/sizeof(_Index1400[0]), 0x1400},
  { (subindex*)_Index1600,sizeof(_Index1600)/sizeof(_Index1600[0]), 0x1600},
  { (subindex*)_Index6200,sizeof(_Index6200)/sizeof(_Index6200[0]), 0x6200},
};

const indextable * _scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1002: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;*callbacks = _Index1200_callbacks; break;
		case 0x1400: i = 5;*callbacks = _Index1400_callbacks; break;
		case 0x1600: i = 6;*callbacks = _Index1600_callbacks; break;
		case 0x6200: i = 7;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status _PDO_status[1] = {s_PDO_status_Initializer};

const quick_index _firstIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  6, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index _lastIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  6, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 _ObjdictSize = sizeof(_objdict)/sizeof(_objdict[0]); 

CO_Data _Data = CANOPEN_NODE_DATA_INITIALIZER();

